development: &default
  adapter: postgresql
  encoding: unicode
  database: dmud_development
  pool: 5
  host: 127.0.0.1
  port: 5432
# FIXME this is super dumb
  username: RESETTE
  password:

test:
  <<: *default
  database: dmud_test

production:
  <<: *default
  database: dmud_production
